// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaxQyPVA9NdIwCZTFvrtm6NLIZAce23rw',
    appId: '1:190844926718:web:0c334b69a8b5600abe03af',
    messagingSenderId: '190844926718',
    projectId: 'fir-ui-practise',
    authDomain: 'fir-ui-practise.firebaseapp.com',
    storageBucket: 'fir-ui-practise.appspot.com',
    measurementId: 'G-W0J7PL9VBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoXgzSGY-gLp3dzZpdSM6WRqhyfnDuo2Y',
    appId: '1:190844926718:android:15fb5b48751397f6be03af',
    messagingSenderId: '190844926718',
    projectId: 'fir-ui-practise',
    storageBucket: 'fir-ui-practise.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEYbFZY5F7grVdNgg3cM3lDH3ztNiX6vs',
    appId: '1:190844926718:ios:240b429fcb522843be03af',
    messagingSenderId: '190844926718',
    projectId: 'fir-ui-practise',
    storageBucket: 'fir-ui-practise.appspot.com',
    androidClientId: '190844926718-4ark0ev4hjoqcr86fer042o3u7vd5u57.apps.googleusercontent.com',
    iosClientId: '190844926718-koon0iru3b5t8f7tcu0f3p3jmaf85l7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUiPractise',
  );
}
